//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _221_Kubar_02
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialType
    {
        public int materialType1 { get; set; }
        public double DefectPercent { get; set; }
    }
}
